<?php

declare(strict_types=1);

namespace Careminate\Module\Cache;

use Careminate\Exception\Module\ModuleCacheException;
use Careminate\Foundation\Version;
use Careminate\Module\ModulePlan;
use JsonException;
use Throwable;

final readonly class ModuleCache
{
    private const int SCHEMA_VERSION = 1;

    public function load(string $path): ?ModulePlan
    {
        if (!is_file($path)) {
            return null;
        }

        $contents = file_get_contents($path);

        if ($contents === false) {
            throw new ModuleCacheException(sprintf(
                'Unable to read module cache "%s".',
                $path,
            ));
        }

        try {
            $data = json_decode($contents, true, flags: JSON_THROW_ON_ERROR);
        } catch (JsonException $exception) {
            throw new ModuleCacheException(sprintf(
                'Module cache "%s" contains invalid JSON: %s',
                $path,
                $exception->getMessage(),
            ));
        }

        if (!is_array($data)) {
            throw new ModuleCacheException(
                'The module cache must contain a JSON object.',
            );
        }

        if (($data['schema'] ?? null) !== self::SCHEMA_VERSION) {
            throw new ModuleCacheException(
                'The module cache schema is incompatible.',
            );
        }

        if (($data['framework_version'] ?? null) !== Version::VERSION) {
            throw new ModuleCacheException(
                'The module cache was generated by another framework version.',
            );
        }

        $plan = $data['plan'] ?? null;

        if (!is_array($plan)) {
            throw new ModuleCacheException(
                'The module cache does not contain a valid plan.',
            );
        }

        return ModulePlan::fromArray($plan);
    }

    public function write(string $path, ModulePlan $plan): void
    {
        $directory = dirname($path);

        if (
            !is_dir($directory)
            && !mkdir($directory, 0775, true)
            && !is_dir($directory)
        ) {
            throw new ModuleCacheException(sprintf(
                'Unable to create module cache directory "%s".',
                $directory,
            ));
        }

        try {
            $contents = json_encode(
                [
                    'schema' => self::SCHEMA_VERSION,
                    'framework_version' => Version::VERSION,
                    'generated_at' => gmdate(DATE_ATOM),
                    'plan' => $plan->toArray(),
                ],
                JSON_THROW_ON_ERROR
                | JSON_PRETTY_PRINT
                | JSON_UNESCAPED_SLASHES,
            );
        } catch (JsonException $exception) {
            throw new ModuleCacheException(sprintf(
                'Unable to encode the module cache: %s',
                $exception->getMessage(),
            ));
        }

        try {
            $temporaryPath = $path . '.tmp.' . bin2hex(random_bytes(6));
        } catch (Throwable $exception) {
            throw new ModuleCacheException(
                'Unable to create a secure temporary cache filename.',
                previous: $exception,
            );
        }

        if (file_put_contents($temporaryPath, $contents, LOCK_EX) === false) {
            throw new ModuleCacheException(sprintf(
                'Unable to write temporary module cache "%s".',
                $temporaryPath,
            ));
        }

        if (!rename($temporaryPath, $path)) {
            @unlink($temporaryPath);

            throw new ModuleCacheException(sprintf(
                'Unable to atomically replace module cache "%s".',
                $path,
            ));
        }
    }
}
